### ISSUE TITLE
The Signup section in the footer is not functional 

### ISSUE THREAD

**Issue by legendarykamal** [GitBolt/stellarsol-website#1]
The signup section in the footer is not functional 

![image](https://user-images.githubusercontent.com/95926324/209478912-c88dfab6-d912-476f-b937-235fee7af1e5.png)

**Comment by GitBolt** [comment]
wow you found it haha! this code is for previous website which wasn't launched, the current website was launched just today actually but we did not announce it yet due to some fixes like this footer as you have mentioned. surprised that you saw this

**Comment by legendarykamal** [comment]
> wow you found it haha! this code is for previous website which wasn't launched, the current website was launched just today actually but we did not announce it yet due to some fixes like this footer as you have mentioned. surprised that you visited our website which is not even announced yet.

oh ok , so where's the code for the new website ?
